### ISSUE TITLE
Missing translation in : Labs (Pinning feature) and Room Invite

### ISSUE THREAD

**Issue by JDixmier** [dinsic-pim/riot-web#257]
Labs (Pinning feature):
![07c835dd592a1893c6ed1185455320d7f08a645f](https://user-images.githubusercontent.com/45665538/171003701-c414d264-6388-442a-b947-e7f3ebc5d04b.png)

Room Invite: issue we are you invited into a room : "Do you want to join "

**Comment by estellecomment** [comment]
Should we remove this pinning feature ? I think this is the element pinning, and we don't support it in Tchap.
@giomfo do you know ? 

Check if this was present in 2.3.7

**Comment by estellecomment** [comment]
![image](https://user-images.githubusercontent.com/911434/171370728-4a780164-fb98-4997-81bf-78123da5882c.png)

**Comment by estellecomment** [comment]
Pinning is first mentioned in element changelog in v0.13.0-rc.1 - 2017-11-10
Released in v0.13.0 - 2017-11-15

**Comment by estellecomment** [comment]
element web v.0.13.0 (which introduces pinning) uses "matrix-react-sdk": "0.11.0"
Tchap-web 2.3.7 uses matrix-react-sdk forked from element's 1.0.7 (probably)
So **pinning was already present in tchap-web 2.3.7's code.**

~~We don't know what the deployed config for 2.3.7 was because it wasn't documented, but~~ 
Looking at the build in https://github.com/tchapgouv/tchap-web/releases/tag/v2.3.7-tchap, config.sample.json in 2.3.7 contains `"feature_pinning": "labs"`.
So **pinning was ~~probably~~ already in Labs in 2.3.7**

**Comment by estellecomment** [comment]
Keeping it in 2.5.0 for now.
We need to fix the translation.
