### ISSUE TITLE
Explore if Tchap Web v2 is compatible with mainlining

### ISSUE THREAD

**Issue by jdauphant** [dinsic-pim/riot-web#292]
## Regressions
- [x] #295
- [x] #296
- [x] #297
## API Changes
- [x] #298
- [x] #294
- [x] #293
- [x] #299
- [x] #300

**source**:  https://docs.google.com/document/d/1vzjZgauLAMvsjVUdxLnqYkqf2GHKZcQupooEVutfmVA/edit?pli=1#heading=h.hl9xdcqvj2py

**Comment by jdauphant** [comment]
- https://github.com/tchapgouv/tchap-web/issues/285

**Comment by mcalinghee** [comment]
At this moment, the mainlining is a `transition` version meaning the former APIs and newer APIs are available.

We could apply the following migration strategy for the client : 
- Resolves the Regression issues : #296 and #297 
- Build a new version of tchap-web-v2
- Release tchap-web-v2 - 2.5.5 to : 
   - [x] dev
   - [ ] preprod
   - [ ] prod
- Perform Tests against :
   - [x] the version "v1.2" (mainlining version) : https://www.tchap.incubateur.net/ 
   - [ ] the version "r0.6.0" (current version) : https://www.beta.tchap.gouv.fr/
- Focus on tchap-web-v4

**Benefits :** 
- Upgrade to v1.2(mainlining) can happen independently
- API Changes issues will be resolved in tchap-web-v4 directly instead of spending effort of fixing issues. in tchap-web-v2

**Caveat :**
- Future upgrades of Synapse(no former API are available) should be performed after tchap-web-v4 is released as the API Changes issues should be resolved

**Participants to this discussion** : @celiacheff , @guillaumevillemont , @jdauphant , @mcalinghee

**Comment by mcalinghee** [comment]
Test performed on dev with mainlining version : https://www.tchap.incubateur.net  :white_check_mark:
- Looking up a user
- Inviting an external user
- Account Registration
- Sign-in
- Sending message
